### ISSUE TITLE
Add block weight

### ISSUE THREAD

**Issue by jnewbery** [bitcoinops/btc-dashboard#2]
Block size is interesting (https://dashboard.bitcoinops.org/d/K7C9p0vmz/btc-number-of-txns-total-fee-per-block-volume?panelId=7&fullscreen&orgId=1) but it'd also be nice to see block weight to see how full blocks are.

**Comment by marcinja** [comment]
Block weight is tracked in the  `total_weight` field (and `segwit_total_weight` for segwit transactions separately).

I just copied the "Block Size" graph and changed the query to use the weight field. The graph shows an average over 144 and 12 blocks, but we can add a graph to track weight by block if you think that's interesting too.

https://dashboard.bitcoinops.org/d/K7C9p0vmz/btc-number-of-txns-total-fee-per-block-volume?panelId=8&fullscreen&orgId=1

**Comment by jnewbery** [comment]
Great. Thanks @marcinja !

@moscos - is this what you were looking for?
