### ISSUE TITLE
What does the total fee view in "BTC: Number of txns, total fee per block, volume" show?

### ISSUE THREAD

**Issue by Xekyo** [bitcoinops/btc-dashboard#4]
I was looking at https://dashboard.bitcoinops.org/d/K7C9p0vmz/btc-number-of-txns-total-fee-per-block-volume?panelId=6&fullscreen&orgId=1, but it's not clear from the values and the name of the chart what I'm looking at. I thought that the chart might be the total fee over 144 blocks, but how then would the fee over 12 blocks be almost the same?

![Screenshot from 2021-03-03 16-35-22](https://user-images.githubusercontent.com/4060799/109875657-bb78ba00-7c3e-11eb-8acb-cbbcdc8e93ab.png)

I suspect that potentially the values in the chart are off, but the chart should probably be renamed to make it easier to understand what it is showing.

**Comment by jnewbery** [comment]
Hmm, here's the query:

```
SELECT
  $__time("time"),
  avg("total_fee" / 1000000) 
    OVER(ORDER BY time ROWS BETWEEN 144 PRECEDING AND CURRENT ROW) AS "Total fee (144blk avg)",
  avg("total_fee" / 1000000) 
    OVER(ORDER BY time ROWS BETWEEN 12 PRECEDING AND CURRENT ROW) AS "Total fee (12blk avg)" 
FROM  dashboard_data_v2
WHERE
  $__unixEpochFilter("time")
ORDER BY time
```

where `total_fee` is the total fee in the block (in sats).

Looks like these values are off by a factor of 100, since those total_fee should be divided by 1e8 to get BTC, not 1e6.

**Comment by Xekyo** [comment]
Yeah, that would make sense! I was trying to find that query in this repo, but could not. Is this only part of the project? There doesn't seem to be a second project corresponding to the Dashboard in this organization.

**Comment by 0xB10C** [comment]
Queries are part of the individual dashboards in Grafana. Could make sense to export the dashboards put the JSON files under version control somewhere.

![image](https://user-images.githubusercontent.com/19157360/110210684-173b8100-7e93-11eb-8d22-00992d1b0b89.png)
(button in the top right of this screenshot)

**Comment by jnewbery** [comment]
@Xekyo - does the new mBTC graph look correct to you?

**Comment by murchandamus** [comment]
Yep, now looks like it's in a reasonable range! Thanks!
